### ISSUE TITLE
Contribute a default value for `githubToken` input

### ISSUE THREAD

**Issue by dbeg** [launchdarkly/find-code-references#12]
A consumer of this action shouldn't need to supply a GitHub token when a default could be used which would still allow consumers to specify a token if needed.

Example from the official GitHub `setup-node` action: https://github.com/actions/setup-node/blob/main/action.yml#L21

**Comment by vlymar** [comment]
Thanks for the submission @dbeg. I agree with the recommendation and we'll merge the PR linked to this issue as soon as we have a chance to test it.
