### ISSUE TITLE
Monorepo support for only scanning specific sub directories

### ISSUE THREAD

**Issue by shadoath** [launchdarkly/find-code-references#15]
Can an option be added to only scan a specific folder or folders?

**Comment by InTheCloudDan** [comment]
@shadoath Apologies for the delay on replying. I'll file this as a feature request. 

To confirm out of the monorepo you are only looking to scan a specific subdirectory, or multiple directories at the same level to look for flags for a single LaunchDarkly project?

**Comment by InTheCloudDan** [comment]
@shadoath when you mentioned multiple Environments, do you mean multiple different LaunchDarkly Projects within that code base? Code Refs scans for Flags which live globally under the Project. I just want to make sure we're working towards the right issue.

**Comment by shadoath** [comment]
Heya Dan, I responded in a rush last time.

Yes, we have multiple LaunchDarkly projects in one codebase.  My thought is that we could specify each project's src folder and then have LD scan in that folder only for it's flags.  That said we have more than 12 folders in the root of our mono repo and only two of them contain LD flags that need to be scanned for.

As it stands right now it does work, I'm thinking it could be more efficient though.

**Comment by InTheCloudDan** [comment]
@shadoath with release `v2.5.1` you should now be able to specify multiple projects and a starting directory for them. Here's instructions for what the configuration file would need: https://github.com/launchdarkly/ld-find-code-refs/blob/master/docs/CONFIGURATION.md#projects

Please let us know if you have any issues.
