### ISSUE TITLE
warning: debug option 'false' unknown; try LD_DEBUG=help

### ISSUE THREAD

**Issue by avrilanne** [launchdarkly/find-code-references#17]
We are getting this message with Run launchdarkly/find-code-references@v8.
It is occasionally breaking this action.

Maybe it is coming from here: https://github.com/launchdarkly/find-code-references/blob/ffc8030dc428ce69161e6960914693c7bf3d6d37/action.yml#L25

**Comment by InTheCloudDan** [comment]
@avrilanne would it be possible for you to update to the latest action version of `v11` and see if that resolves the issue?

**Comment by avrilanne** [comment]
@InTheCloudDan I am trying bumping the action version. Thank you!

**Comment by InTheCloudDan** [comment]
Since there has been no additional followup, closing for now. Please re-open if this is still an issue.
