### ISSUE TITLE
Action fails on forked repositories

### ISSUE THREAD

**Issue by rarichard** [launchdarkly/find-code-references#24]
AFAIK, secrets aren't available on forks, so anytime someone forks our repo the action fails to run because the LaunchDarkly secret is missing. 

Any ideas to mitigate?

**Comment by jazanne** [comment]
Hi @rarichard, I would recommend setting up this action so that it doesn't run on PRs from forks or forks themselves, but still runs once they are merged. At this time I don't believe there is a GHA best practice for running an action with secrets in forks.
