### ISSUE TITLE
Tag numbering causes Dependabot to produce erroneous update PRs

### ISSUE THREAD

**Issue by polish-ambassador-ftn** [launchdarkly/find-code-references#25]
Hey! It appears that the tag numbering in this repository confuses Dependabot. See here:
![Screen Shot 2022-07-12 at 4 36 58 PM](https://user-images.githubusercontent.com/95660502/178616353-e1753540-b3e5-49f5-b313-47ca8bb1b257.png)
.

**Comment by jacobScottAllen** [comment]
Thank you for bringing this to our attention, the team sees this and we will investigate our options!

**Comment by carmenquan** [comment]
Hi @polish-ambassador-ftn, we've unpublished those older versions from the marketplace which hopefully will resolve this issue. Feel free to reopen if you see anything unexpected - thank you!

**Comment by jazanne** [comment]
We have identified that this issues persists.
