### ISSUE TITLE
LaunchDarkly API responded with status code 403

### ISSUE THREAD

**Issue by dc185334** [launchdarkly/find-code-references#32]
For the latest one 2.8.0, with example action with only changes we did - create repo secret and named LD_Project_Key with string:

`helpers.go:39: error creating repository: LaunchDarkly API responded with status code 403`

![image](https://user-images.githubusercontent.com/79466025/211522552-c7165d18-e446-4b97-ba46-d4066221ef47.png)

**Comment by jazanne** [comment]
Hi @dc185334, can you tell us what version of code refs you were using previously?

Can you also confirm that the access token being used as permission to [create and update repos](https://docs.launchdarkly.com/home/members/role-actions?q=action#code-reference-actions)?

**Comment by dc185334** [comment]
> Hi @dc185334, can you tell us what version of code refs you were using previously?
> 
> Can you also confirm that the access token being used as permission to [create and update repos](https://docs.launchdarkly.com/home/members/role-actions?q=action#code-reference-actions)?

I can tell it does not fail anylonger since I did downgrade action version in workflow down to 2.6.*

```
DEBUG: 2023/01/10 14:58:38 git.go:152: identified head sha: 0f9c0a464382b2f6dddcd50a8d53e1e512b954a2
DEBUG: 2023/01/10 14:58:38 client.go:582: [DEBUG] GET https://app.launchdarkly.com/api/v2/code-refs/repositories/office
DEBUG: 2023/01/10 14:58:38 client.go:582: [DEBUG] POST https://app.launchdarkly.com/api/v2/code-refs/repositories
```

But what I see within those files is confusing me a bit, since there is a link to non existent repos within my org:
`{"_links":{"self":{"href":"/api/v2/code-refs/repositories","type":"application/json"}},"items":[{"name":"github-standards","sourceLink":"https://github.com/my-orv/github-standards","commitUrlTemplate":"https://github.com/my-org/github-standards/commit/${sha}","hunkUrlTemplate":"https://github.com/my-org/github/standards/blob/${sha}/${filePath}#L${lineNumber}","type":"github","defaultBranch":"main","enabled":true,"version":1,"_links":{"branches":[],"self":{"href":"/api/v2/code-refs/repositories/github-standards","type":"application/json"}},"_access":{"denied":[{"action":"createCodeRefsRepository","reason":{"effect":"deny"}},{"action":"updateCodeRefsRepositoryName","reason":{"effect":"deny"}},{"action":"updateCodeRefsRepositoryConfiguration","reason":{"effect":"deny"}},{"action":"updateCodeRefsRepositoryOn","reason":{"effect":"deny"}},{"action":"updateCodeRefsRepositoryBranches","reason":{"effect":"deny"}},{"action":"deleteCodeRefsRepository","reason":{"effect":"deny"}}],"allowed":[]}}]}`

I'll try to figure out is Admin role of project and regular admin token permissions allows for such activity.

Thank you for your reply, @jazanne

**Comment by tappin-kr** [comment]
Am seeing the same error.

error creating repository: LaunchDarkly API responded with status code 403

Have tried the following 2 auth tokens with no success
![image](https://user-images.githubusercontent.com/65632059/227632841-6c6037fd-d757-476f-bf46-bce8261e6db4.png)

![image](https://user-images.githubusercontent.com/65632059/227632898-d102a704-279c-40da-8c0f-ad2de138c3e0.png)


![Screenshot 2023-03-24 at 1 18 21 PM](https://user-images.githubusercontent.com/65632059/227632618-160289c1-20d1-4a33-ac34-a581dd97694f.png)
![Screenshot 2023-03-24 at 1 19 29 PM](https://user-images.githubusercontent.com/65632059/227632624-4c6343f6-20c7-4bfb-9602-6e1e410744d0.png)
![Screenshot 2023-03-24 at 1 18 56 PM](https://user-images.githubusercontent.com/65632059/227632628-f62a0bfd-1031-4101-82a8-76e32ec57aef.png)

**Comment by jazanne** [comment]
@tappin-kr thank you for the additional details. I will share these with the team.

Have you ever had code refs running successfully in the past with a different token? Or is this the first try at getting it setup?

**Comment by tappin-kr** [comment]
Had an admin create the role, it is now working. Thank you.

**Comment by jazanne** [comment]
@tappin-kr glad to here, thank you for the details. I will pass them on to see if we can make this clearer in the future
