### ISSUE TITLE
Actions running for hours

### ISSUE THREAD

**Issue by williamatpaper** [launchdarkly/find-code-references#33]
Hi all,

I figured I'd put in an issue for this action. We have the fetch-depth option set to 11.

The action stalls after: 
```INFO: 2023/01/24 23:11:07 coderefs.go:148: sending 267 code references across 401 flags and 169 files to LaunchDarkly for project(s): [ default]

INFO: 2023/01/24 23:11:07 coderefs.go:182: checking if 320 flags without references were removed in the last 11 commits for project: default
```

**Comment by jazanne** [comment]
Thank you for submitting this issue, the team is looking into the problem.

In the interim, reducing the `fetch-depth` and `lookback` to a fewer number of commits for extinctions scanning should reduce the likelihood of this occurring. More infomation about the `lookback` configuration option can be found here: https://github.com/launchdarkly/ld-find-code-refs/blob/main/docs/CONFIGURATION.md and https://docs.launchdarkly.com/home/code/code-references#understanding-extinction-events

**Comment by jazanne** [comment]
@williamatpaper We just release [2.9.2](https://github.com/launchdarkly/find-code-references/releases/tag/v2.9.2) which should fix the issue with the action running for hours and timing out. Please let use know if you have any further issues.
