### ISSUE TITLE
skipping code reference pruning: authentication required

### ISSUE THREAD

**Issue by rpearce** [launchdarkly/find-code-references#46]
Hi, great LD folx,

We happened to notice in the logs this warning:

```
INFO: 2023/12/28 17:52:26 coderefs.go:199: attempting to prune old code reference data from LaunchDarkly
WARNING: 2023/12/28 17:52:26 coderefs.go:202: unable to retrieve branch list from remote, skipping code reference pruning: authentication required
```

Our workflow follows your examples, and we are providing our `accessToken` and `projKey` correctly, so I'm wondering if this is something we should be concerned about?

Thanks for your time!

**Comment by jazanne** [comment]
@rpearce This error can safely be ignored. We are working on implementing a change to silence it in future versions. Sorry for the incovenience
